# Generated by Django 3.0.8 on 2020-07-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, help_text='Use Image for Im-powring your Blog', upload_to=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='priority',
            field=models.IntegerField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='blog',
            name='similar_post',
            field=models.ManyToManyField(blank=True, null=True, related_name='_blog_similar_post_+', to='blog.Blog'),
        ),
    ]
