# Generated by Django 3.0.8 on 2020-07-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200712_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='parsed_content',
            field=models.TextField(default='dcfsdwfc', max_length=5000),
            preserve_default=False,
        ),
    ]
