# Generated by Django 3.0.8 on 2020-07-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blog_parsed_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='parsed_content',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
