# Generated by Django 3.0.8 on 2020-07-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200715_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=160)),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=45)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
